---
title: "Git Workshop"
author: "Pau Balaguer<br />Jordi Vilaplana"
date: "6/6/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Git (mini)Workshop for statiticians.

## Prerequisites
Download and install git and create a GitHub account.

- [git](https://git-scm.com/downloads)
- [GitHub Account](https://github.com/)


## Git Basics
Basic git commands.

| Command | Description |
| ------- | ----------- |
| `git init` | Create a new local repository. |
| `git clone` | Clone an existing repository. |
| `git add -A` | Stage (add) all changed files, ready for commit. |
| `git status` | List new or modified files not yet commited. |
| `git commit -a` | Commit all local changes in tracked files. |
| `git commit` | Commit previously staged files. |
| `git push` | Publish local changes to GitHub. |
| `git pull` | Download changes from GitHub. |


## Proposed git workflow

### Start
1. [Create a new repository](https://github.com/organizations/IRBLleida/repositories/new) on GitHub.
2. Checkout the newly created repository in RStudio via `File - New Project ...`.
3. Make changes, commit changes ...
4. Push changes.


### Work
1. Pull changes.
2. Make changes, commit changes ...
3. Push changes.


### Conflicts
1. Make changes, commit changes ...
2. Push changes [Error in push]
3. Pull changes.
4. Resolve conflicts.
5. Commit and push.
